### ISSUE TITLE
cygwin:died waiting for dll loading, errno 11

### ISSUE THREAD

**Issue by onkarojha77** [adoxa/ansicon#102] opened 2017-04-01 14:13 UTC
-bash-4.4$ ./onk.sh
+ rm -f templatesToExport.txt
++ cat tmpids.txt
+ for TEMPLATE in `cat tmpids.txt`
      0 [main] bash 11116 fork: child 9828 - died waiting for dll loading, errno 11
./onk.sh: fork: retry: Resource temporarily unavailable
1218785 [main] bash 11116 fork: child 13056 - died waiting for dll loading, errno 11
./onk.sh: fork: retry: Resource temporarily unavailable
3438711 [main] bash 11116 fork: child 10152 - died waiting for dll loading, errno 11
./onk.sh: fork: retry: Resource temporarily unavailable
7648852 [main] bash 11116 fork: child 6728 - died waiting for dll loading, errno 11
./onk.sh: fork: retry: Resource temporarily unavailable
15871292 [main] bash 11116 fork: child 8724 - died waiting for dll loading, errno 11
./onk.sh: fork: Resource temporarily unavailable
-bash-4.4$ ^C
-bash-4.4$ ^C
-bash-4.4$ cat onk.sh
#!/bin/bash
set -x
rm -f templatesToExport.txt
for TEMPLATE in `cat tmpids.txt`
do
TEMPLATE_ID=`echo $TEMPLATE | cut -d'/' -f2 | cut -d'"' -f1`
echo $TEMPLATE_ID >> templatesToExport.txt
done
-bash-4.4$

**Comment by adoxa** [comment] 2017-04-02 00:35
Duplicate of #100.

**Closed by adoxa** 2017-04-02 00:35 UTC
